logs: 
    - name: root
      level: info
      appenders: 
          - type: FileLogAppender
            file: /home/lqf/cpp/sylar/logData/root.txt
          - type: StdoutLogAppender
          - type: FileLogAppender
    - name: lqf
      level: info
      appenders: 
          - type: FileLogAppender
            file: /home/lqf/cpp/sylar/logData/system.txt
          - type: StdoutLogAppender
